config/routes.rb
GiftYourTime::Application.routes.draw do
  devise_for :users
  root to: 'events#index'
  resources :events, :event_participation
  resources :comments, only: [:create, :destroy]
  get 'search' => 'search#index'
  get 'history'=> 'history#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :event_participation, dependent: :destroy
  validates_presence_of :name, :date, :start_time, :end_time, :user
  validate :time_range

  private
  def time_range
    errors.add(:end_time, "should be greater than event start time") if start_time > end_time
  end
end

app/models/event_participation.rb
class EventParticipation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #attr_accessible :first_name, :last_name
  validates_presence_of :first_name, :last_name
  has_many :event_participation
  has_many :events
  def name
    [first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name , :last_name]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    comment.save!
    redirect_to event_path(comment.event)
  rescue
    render text: "Error creating comment"
  end

  def destroy
    comment = Comment.find(params[:id])
    event_id = comment.event_id
    if comment.user_id == current_user.id
      comment.destroy
      redirect_to event_path(event_id)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :user_id, :event_id)
  end
end

app/controllers/event_participation_controller.rb
class EventParticipationController < ApplicationController
  before_filter :authenticate_user!

  def new
    @event_participation = EventParticipation.new(event_participation_params)
    event = @event_participation.event
    score_value = ((event.end_time - event.start_time) / 1.hour).round
    @event_participation.user.score = @event_participation.user.score - score_value
    @event_participation.user.save!
    @event_participation.save!
    event.user.score = event.user.score + score_value
    event.user.save!
    if params[:tag]=='search'
      redirect_to :back
    else
      redirect_to event_path(@event_participation.event_id)
    end
  end

  def destroy
    event_participation = EventParticipation.where(:user_id => params[:event_participation][:user_id], :event_id => params[:event_participation][:event_id]).limit(1)[0]
    event = event_participation.event
    score_value = ((event.end_time - event.start_time) / 1.hour).round
    event_participation.user.score = event_participation.user.score + score_value
    event_participation.user.save!
    event.user.score = event.user.score - ((event.end_time - event.start_time) / 1.hour).round
    event.user.save!

    event_participation.destroy
    if params[:tag]=='search'
      redirect_to :back
    else
      redirect_to event_path(event_participation.event_id)
    end
  end


  private
  def event_participation_params
    params.require(:event_participation).permit(:user_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @events = Event.all #TODO: all_future_events
    respond_to do |format|
      format.html
      format.json { render json: @events.to_json }
    end
  end

  def new
    flash[:error] = "You must sign in to add an event!"
    redirect_to new_user_session_path and return unless user_signed_in?
    @event = Event.new(date: params[:date], user_id: current_user.id)
  end

  def create
    @event = Event.new(event_parameters)
    @event.save!
    redirect_to events_path
  rescue
    render :new, status: 400
  end

  def show
    @event = Event.where(id: params[:id]).limit(1)[0]
    @event_participants = @event.event_participation
    @all_comments = @event.comments
    @comment = Comment.new(event_id: @event.id, user_id: current_user.id) if user_signed_in?
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.user_id == current_user.id
      @participations = @event.event_participation
      score = ((@event.end_time - @event.start_time) / 1.hour).round
      for i in @participations
          i.user.score = i.user.score +  score
          i.user.save!
      end
      current_user.score = current_user.score - (score * @participations.length)
      current_user.save!
      @event.destroy
      redirect_to events_path
    end
  end

  def edit
    @event = Event.find(params[:id])
    render :edit
  end

  def update
    @event = Event.find(params[:id])
    if @event.user_id != current_user.id
      redirect_to events_url
    else
      @event.name = params[:event][:name]
      @event.description = params[:event][:description]
      @event.date = params[:event][:date]
      oldEndTime = params[:event][:end_time].to_time.strftime("%H:%M")
      oldStartTime = params[:event][:start_time].to_time.strftime("%H:%M")
      if @event.start_time.strftime("%H:%M") != oldStartTime || @event.end_time.strftime("%H:%M") != oldEndTime
        @participations = @event.event_participation
        old_score = ((@event.end_time - @event.start_time) / 1.hour).round
        new_score =  ((params[:event][:end_time].to_time - params[:event][:start_time].to_time ) / 1.hour).round
        for i in @participations
          i.user.score = i.user.score + old_score - new_score
          i.user.save!
        end
        @event.start_time = params[:event][:start_time]
        @event.end_time = params[:event][:end_time]
        current_user.score = current_user.score + (new_score - old_score) * @participations.length
        current_user.save!
        end
    end
    if @event.save
      redirect_to events_url
    else
      render :edit
    end
  end

  private
  def event_parameters
    params.require(:event).permit(:date, :start_time, :end_time, :name, :description, :user_id)
  end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def index
    @organized_events = current_user.events
    @event_participations = EventParticipation.where("user_id = ?",current_user.id).pluck(:event_id)
    @participated_events = Event.where(id: @event_participations)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = params[:query].strip
    @results = Event.where("name ilike ?", "%#{@query}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<h1 class="heading">
  Edit event
</h1>
<div class="form" id="edit-events-container">
  <%= form_for @event do |f|%>
      <div class="large-3 columns small-12">
        <%= f.label "Date" %>
        <span>
        <%= f.label @event.errors[:date].first || " ", class: "error" %>
      </span>
        <%= f.date_field :date %>
      </div>

      <div class="small-4 half-row-control large-1 columns">
        <%= f.label "From" %>
        <span>
        <%= f.label @event.errors[:start_time].first || " ", class: "error" %>
      </span>
        <%= f.text_field :start_time, id: "start_time" %>
      </div>

      <div class="small-4 half-row-control large-1 columns">
        <%= f.label "To" %>
        <span>
        <%= f.label @event.errors[:end_time].first || " ", class: "error" %>
      </span>
        <%= f.text_field :end_time, id: "end_time" %>
      </div>

      <div class="columns large-8 small-12">
        <%= f.label "Event Name" %>
        <span>
        <%= f.label @event.errors[:name].first || " ", class: "error" %>
      </span>
        <%= f.text_field :name %>
      </div>

      <div class="columns large-8 small-12">
        <%= f.label "Event Description" %>
        <span>
        <%= f.label @event.errors[:description].first || " ", class: "error" %>
      </span>
        <%= f.text_area :description %>
      </div>

      <%= f.hidden_field :user_id %>
      <div class="columns">
        <button name="commit" type="submit" class="success-button">Update Event</button>
        <%= link_to "Discard", events_url, class: "button success-button secondary-button" %>
      </div>
  <% end %>
</div>
<%= content_for :custom_js do %>
    <%= javascript_include_tag "events_controller" %>
    <script type="text/javascript">
      $(function () {
        new EventController("#edit-events-container").init();
      });
    </script>
<% end %>

app/views/events/index.html.erb
<%= stylesheet_link_tag "calendar" %>

<div id='calendar'></div>
<div id="event-details">
</div>
<div id="light-box-container" data-reveal class="reveal-modal"></div>
<script type="text/template" id="calendar-template">
    <div class="clndr-controls">
      <span class="clndr-previous-button nav-arrow">&lsaquo;</span>
      <h2 class="title">[%= month %] [%= year %]</h2>
      <span class="clndr-next-button nav-arrow">&rsaquo;</span>
    </div>
    <div class="clndr-grid">
      <div class="days-of-the-week">
        [% _.each(daysOfTheWeek, function(day) { %]
          <div class="header-day grid-cell">[%= day %]</div>
        [% }); %]
        <div class="days clearfix">
          [% _.each(days, function(day) { %]
            <div class="grid-cell [%= day.classes %]">
                <span class="day-text">[%= day.day %]</span>
                <ul class="inline-event-list">
                    [% _.each(day.events, function (evt) {%]
                        [% if (evt.imAttending) { %]
                            <li class="inline-event im-attending" data-event-id="[%=evt.id%]">
                        [%} else {%]
                            <li class="inline-event" data-event-id="[%=evt.id%]">
                        [%}%] <span class="inline-event-description"> [%= evt.formattedStartTime %] [%= evt.title%]</span></li>
                    [%});%]
                </ul>
            </div>
          [% }); %]
        </div>
      </div>
    </div>
</script>

<script type="text/template" id="event-details-template">
  <div class="add-event clearfix">
    <div class="date">
      <span id="day-number">[%=dayNumber%]</span> [%=monthName%] [%=year%]
      </div>
    <a class="add-event-button" href="<%=new_event_path()%>?date=[%=date%]">Add an event</a>
  </div>
  <ul class="events-in-day-list">
    [% _.each(events, function (event) { %]
      <li>
        <div class="event-timing">
          <div>[%= event.formattedStartTime %]</div>
          [% if (event.imAttending) {%]
            <div class="small-text">I&#39;m attending</div>
          [% } %]
        </div>
        <div class="event-details">
          <div class="event-title">[%= event.title %]</div>
          <div class="small-text">[%= event.description %]</div>
          <div class="event-eta">[%= event.eta %]</div>
        </div>
      </li>
    [% });%]
  </ul>
  [% if(!isMobile) {%]
    <a class="close-reveal-modal">&#215;</a>
  [% } %]
</script>

<%= content_for :custom_js do %>
    <%= javascript_include_tag "calendar_controller" %>
    <script type="text/javascript">
      $(function () {
        new CalendarController("#calendar", window.Calendar).init();
      });
    </script>
<% end %>

app/views/events/new.html.erb
<h1 class="heading">
  Add an event
</h1>
<div class="form" id="create-events-container">
  <%= form_for @event do |f|%>
      <div class="large-3 columns small-12">
        <%= f.label "Date" %>
        <span>
        <%= f.label @event.errors[:date].first || " ", class: "error" %>
      </span>
        <%= f.date_field :date %>
      </div>

      <div class="small-4 half-row-control large-1 columns">
        <%= f.label "From" %>
        <span>
        <%= f.label @event.errors[:start_time].first || " ", class: "error" %>
      </span>
        <%= f.text_field :start_time, id: "start_time" %>
      </div>

      <div class="small-4 half-row-control large-1 columns">
        <%= f.label "To" %>
        <span>
        <%= f.label @event.errors[:end_time].first || " ", class: "error" %>
      </span>
        <%= f.text_field :end_time, id: "end_time" %>
      </div>

      <div class="columns large-8 small-12">
        <%= f.label "Event Name" %>
        <span>
        <%= f.label @event.errors[:name].first || " ", class: "error" %>
      </span>
        <%= f.text_field :name,  placeholder: "Enter event description" %>
      </div>

      <div class="columns large-8 small-12">
        <%= f.label "Event Description" %>
        <span>
        <%= f.label @event.errors[:description].first || " ", class: "error" %>
      </span>
        <%= f.text_area :description, placeholder: "Enter event description" %>
      </div>

      <%= f.hidden_field :user_id %>
      <div class="columns">
      <button name="commit" type="submit" class="success-button">Create Event</button>
      <%= link_to "Discard", events_url, class: "button success-button secondary-button" %>
      </div>
  <% end %>
</div>

<%= content_for :custom_js do %>
    <%= javascript_include_tag "events_controller" %>
    <script type="text/javascript">
      $(function () {
        new EventController("#create-events-container").init();
      });
    </script>
<% end %>

app/views/events/show.html.erb
<div class="event">
  <div class="columns small-12 large-8">
    <h1 id="event-name-header" class="header"><%= @event.name %></h1>
    <div class="event-details-container clearfix">
        <div class="label-value-container small-12 large-4 columns">
          <div class="label">Date</div>
          <div class="value"><%= @event.date.strftime("%d-%b-%Y") %></div>
        </div>
        <div class="label-value-container small-4 large-2 columns">
          <div class="label">From</div>
          <div class="value"><%= @event.start_time.strftime("%I:%M %p") %></div>
        </div>
        <div class="label-value-container small-4 large-2 columns">
          <div class="label">To</div>
          <div class="value"><%= @event.end_time.strftime("%I:%M %p") %></div>
        </div>
        <div class="label-value-container small-12 large-12 columns">
          <div class="label">Event Name</div>
          <div class="value"><%= @event.name %></div>
        </div>
        <div class="label-value-container small-12 large-12 columns">
          <div class="label">Description</div>
          <div class="value"><%= @event.description %></div>
        </div>
        <% if current_user && @event.user_id == current_user.id %>
          <div class="columns">
            <%= link_to 'Edit Event', edit_event_path, class: "button success-button" %>
            <%= link_to 'Cancel Event', @event, :method => :delete, :confirm => 'Are you sure?', class: "button success-button failure-button" %>
          </div>
        <% else %>
          <div class="label-value-container small-12 large-12 columns">
            <div class="label">Organizer</div>
            <div class="value"><%= @event.user.name %></div>
          </div>
          <div class="columns">
            <% if current_user %>
                <% if EventParticipation.where("user_id =" + current_user.id.to_s+" AND event_id = " +@event.id.to_s).count == 0 %>
                      <%= link_to "Attend this event", new_event_participation_path(:event_participation => {:user_id => current_user.id, :event_id => @event.id}), class: "button success-button" %>
                <% else %>
                      <%= link_to "Unsubscribe from this event", event_participation_path(:event_participation => {:user_id => current_user.id, :event_id => @event.id}), :method => :delete, class: "button success-button failure-button" %>
                <% end %>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
  <div id="participants-container" class="columns small-12 large-4">
    <h4 class="header" id="participants-header"><%=image_tag "participants-icon.png", class: "header-icon" %> Participants (<%= @event_participants.count %>)</h4>
    <ul class="user-name-list">
      <% @event_participants.each do |event_participant| %>
          <li class="user-name-list-item">
            <div class="user-name"><%= event_participant.user.name %></div>
          </li>
      <% end %>
    </ul>
  </div>
  <div id="comments-container" class="columns small-12 large-8">
      <h4 class="header" id="comments-header"><%=image_tag "comments-icon.png", class: "header-icon" %> Comments (<%= @all_comments.count %>)</h4>
      <% if user_signed_in? %>
          <%= form_for @comment do |f| %>
              <div>
                <%= f.text_area :body, placeholder: "Post your queries/suggestions/comments here", class: "row" %>
                <%= f.hidden_field :user_id %>
                <%= f.hidden_field :event_id %>
                <button name="commit" type="submit" class="button success-button secondary-button">Submit</button>
              </div>
          <% end %>
      <% end %>
      <ul class="comment_listing">
        <% @all_comments.each do |comment| %>
            <li>
              <div class="user-name"><%= comment.user.name %> <span class="small-text">wrote:</span></div>
              <div class="comment-posted-time"><%= time_ago_in_words(comment.created_at) + " ago" %></div>
              <p>
                <%= comment.body %>
              </p>
              <%= link_to 'Delete', comment_path(comment.id), :method => :delete if current_user && comment.user_id == current_user.id %>
            </li>
        <% end %>
      </ul>
  </div>
</div>

app/views/history/index.html.erb
<div class="event-listing-container">
  <% if @organized_events.present? %>
  <h1 class="heading">
    Events you organized
  </h1>
  <ul class="search-results-list">
    <% @organized_events.each do |event| %>  
    <li class="search-result-item clearfix">
      <div class="date-indicator columns large-1 small-3">
        <div class="date-info-holder">
          <div class="day-date-icon">
            <div class="day-name small-text"><%=event.date.strftime("%a")%></div>
            <div class="day-number"><%=event.date.strftime("%d")%></div>
          </div>
          <div class="small-text"><%=event.date.strftime("%b")%> <%=event.date.strftime("%Y")%></div>
        </div>
      </div>
      <div class="columns large-2 small-3 time-range">
        <div><%= event.start_time.strftime("%I:%M %P") %> </div>
        <div>to</div>
        <div><%= event.end_time.strftime("%I:%M %P") %></div>
      </div>
      <div class="columns large-9 small-6">
        <div class="event-name"><%= link_to event.name, event_url(event.id) %></div>
        <div class="small-text"><%= time_ago_in_words(event.date)%> ago</div>
      </div>
    </li>
    <%end%>
  </ul>
  <%end%>
  <% if @participated_events.present? && @participated_events != @organized_events%>
  <h1 class="heading"> Events you attended </h1>
  <ul class="search-results-list">
    <% @participated_events.each do |event| %>
    <li class="search-result-item clearfix">
      <div class="date-indicator columns large-1 small-3">
        <div class="date-info-holder">
          <div class="day-date-icon">
            <div class="day-name small-text"><%=event.date.strftime("%a")%></div>
            <div class="day-number"><%=event.date.strftime("%d")%></div>
          </div>
          <div class="small-text"><%=event.date.strftime("%b")%> <%=event.date.strftime("%Y")%></div>
        </div>
      </div>
      <div class="columns large-2 small-3 time-range">
        <div><%= event.start_time.strftime("%I:%M %P") %> </div>
        <div>to</div>
        <div><%= event.end_time.strftime("%I:%M %P") %></div>
      </div>
      <div class="columns large-9 small-6">
        <div class="event-name"><%= link_to event.name, event_url(event.id) %></div>
        <div class="small-text"> by <%= event.user.name %> </div>
        <div class="small-text"><%= time_ago_in_words(event.date)%> ago</div>
      </div>
    </li>
    <%end%>
  </ul>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400,300' rel='stylesheet' type='text/css'>
  <title><%= content_for?(:title) ? yield(:title) : "Gift your time!" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render "shared/top_bar" %>

  <div id="notice-msgs" class="hide"><%= notice %></div>
  <div id="alert-msgs" class="hide"><%= alert %></div>

  <%= yield %>
  <%= javascript_include_tag "application" %>
  <%= yield :custom_js %>
  <script type="text/javascript">
    new NotificationController("#notice-msgs", "#alert-msgs").showNotifications();
  </script>
</body>
</html>

app/views/search/index.html.erb
<div class="event-listing-container">
  <% if @results.present? %>
      <div class="search-results-summary"><%= pluralize( @results.count, 'event' ) %> found</div>
      <ul class="search-results-list">
        <% @results.each do |event| %>
          <li class="search-result-item clearfix">
            <div class="date-indicator columns large-1 small-3">
              <div class="date-info-holder">
                <div class="day-date-icon">
                  <div class="day-name small-text"><%=event.date.strftime("%a")%></div>
                  <div class="day-number"><%=event.date.strftime("%d")%></div>
                </div>
                <div class="small-text"><%=event.date.strftime("%b")%> <%=event.date.strftime("%Y")%></div>
              </div>
            </div>
            <div class="columns large-2 small-3 time-range">
              <div><%= event.start_time.strftime("%I:%M %P") %> </div>
              <div>to</div>
              <div><%= event.end_time.strftime("%I:%M %P") %></div>
            </div>
            <div class="columns large-3 small-6">
              <div class="event-name"><%= link_to event.name,event_url(event) %></div>
              <div class="small-text"> by <%= event.user.name %> </div>
            </div>
            <div class="columns large-2 show-for-large-up">
              <div class="columns large-12 gray-text"><%= image_tag "participants-icon.png", class: "icon-small"%> Participants (<%= event.event_participation.count%>)</div>
              <div class="columns large-12 gray-text"><%= image_tag "comments-icon.png", class: "icon-small"%> Comments (<%= event.comments.count%>)</div>
            </div>
            <div class="columns large-3 show-for-large-up button-holder">
                    <% if current_user && current_user.id == event.user_id %>
                        <% if current_user.id == event.user_id %>
                            <span> You are the organizer</span>
                        <% end %>
                        <% else %>
                      <% if EventParticipation.where("user_id =" + current_user.id.to_s+" AND event_id = " + event.id.to_s).count == 0 %>
                   <%= link_to "Attend this event", new_event_participation_path(:event_participation => {:user_id => current_user.id, :event_id => event.id}, :tag =>'search')%>
                       <% else %>
                   <%= link_to "Unsubscribe from this event", event_participation_path(:event_participation => {:user_id => current_user.id, :event_id => event.id},:id =>event.id, :tag => 'search'), :method => :delete %>
            <% end %>
                  <% end %>
            </div>
          </li>
        <% end %>
      </ul>
  <% else %>
     <h3> No events found.</h3>
  <% end %>

</div>

app/views/shared/_top_bar.html.erb
<nav class="top-bar" data-options="is_hover: false" data-topbar>
  <ul class="title-area">
    <h1>
     <a href= '/' class="nav-item-text">
       <%= image_tag asset_path('clock.png'), :class => "logo" %>
       Gift your Time
     </a>
   </h1>
    </ul>
  <section class="top-bar-section">
      <!--<li class="toggle-topbar menu-icon"><a href="#"></a></li>-->
    <ul class="right">
      <li class="has-form">
       <div class="row collapse">
         <%= form_tag :search, :method => :get do %>
             <%= text_field_tag :query, params[:query], :placeholder => "Search an event", :id => "search-text"%>
        <% end %>
      </div>
    </li>

    <li class="divider"></li>
    <% if user_signed_in? %>
      <li class="has-dropdown">
            <a href="#"><%= current_user.name %>
            <%= current_user.score %></a>
        <ul class="dropdown">
          <li><%= link_to "Events History", history_url %></li>
          <li><%= link_to "Change Password", edit_user_registration_url %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
        </ul>
      </li>
    <% else %>
    <li class="has-form">
      <%= link_to "Login", new_user_session_path, class: 'button' %>
    </li>
    <li class="divider"></li>
    <li class="has-form">
      <%= link_to "Register", new_user_registration_path, class: 'button' %>
    </li>
    <% end %>
  </ul>
</section>
</nav>